In [ ]:
!git clone https://github.com/jsaj/MDSCPDP.git

In [ ]:
!pip install deslib

In [38]:
from MDS_CPDP.mdscpdp import MDSCPDP

import pandas as pd
from glob import glob

import warnings
warnings.filterwarnings("ignore")

In [39]:

# path of datasets to predict
path = '/content/MDS_CPDP/benchmark-execution/benchmarks/datasets/RELINK/*'

# read and create dataframe (dataset) with all projects for predict
dataset = []
for project_url in glob(path):
  productName = project_url.split('/')[len(project_url.split('/'))-1]
  df = pd.read_csv(project_url)
  df.insert(0, 'productName', productName)
  dataset.append(df)
dataset = pd.concat(dataset).reset_index(drop=True)

dataset

,productName,isDefective,CountLineCodeExe,AvgCyclomatic,AvgCyclomaticModified,AvgCyclomaticStrict,AvgEssential,AvgLine,AvgLineBlank,AvgLineCode,...,CountStmtDecl,CountStmtExe,MaxCyclomatic,MaxCyclomaticModified,MaxCyclomaticStrict,RatioCommentToCode,SumCyclomatic,SumCyclomaticModified,SumCyclomaticStrict,SumEssential
0,Apache2.0.csv,1,907,12,11,14,4,82,5,61,...,178,738,51,51,56,0.28,221,197,246,81
1,Apache2.0.csv,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.00,0,0,0,0
2,Apache2.0.csv,1,1096,8,7,9,4,54,4,49,...,172,877,45,26,45,0.04,256,217,277,128
3,Apache2.0.csv,0,522,5,5,6,2,37,5,27,...,112,414,25,25,30,0.32,134,122,146,63
4,Apache2.0.csv,0,26,2,2,2,1,21,1,9,...,10,20,4,5,4,0.73,9,10,9,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,openintents.csv,0,18,1,1,1,1,41,4,29,...,13,14,1,1,1,0.25,1,1,1,1
645,openintents.csv,0,22,7,7,7,1,50,10,38,...,13,18,7,7,7,0.27,7,7,7,1
646,openintents.csv,0,64,1,1,1,1,5,0,5,...,40,66,6,6,7,0.01,41,41,42,23
647,openintents.csv,0,85,7,7,11,1,21,3,17,...,27,90,19,19,31,0.16,47,47,71,6
648,openintents.csv,0,5,1,1,1,1,15,3,10,...,10,4,1,1,1,0.96,2,2,2,2

In [40]:
#create MDSCPDP object to predict dataset
obj = MDSCPDP(dataset)

#get MDSCPDP performance after predict the dataset. Return a pandas dataframe
obj.performances

,productName,percentBugs,dynamic_selection,classifier,size_pool,fscore,auc,pf,gmean,precision,recall,accuracy,tn,fp,fn,tp
0,Apache2.0.csv,50.515464,KNORAU,GaussianNB,10,0.70056,0.81431,0.17708,0.721541,0.784810,0.632653,0.726804,79,17,36,62
1,openintents.csv,39.285714,KNORAU,GaussianNB,10,0.42857,0.77406,0.00000,0.522233,1.000000,0.272727,0.714286,34,0,16,6
2,zxing1.6.csv,29.573935,KNORAU,GaussianNB,10,0.07874,0.64123,0.01423,0.204376,0.555556,0.042373,0.706767,277,4,113,5